### ISSUE TITLE
Stuttering playback

### ISSUE THREAD

**Issue by prentice1030** [Darkside138/DiscordSoundboard#105]
Just started using the soundboard version 2.2.2 beta and its awesome but have noticed some stuttering with the audio playback. Its worse in some discord servers than others, would this be an issue more with the soundboard app, an issue with discord itself, the amount of ppl in a discord, or a connection issue, etc?

**Comment by Darkside138** [comment]
Hoping this is fixed now. I've updated the playback library as well as the bot library.
