### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by OBenned** [Darkside138/DiscordSoundboard#106]
I created a repo for a docker version of this.

You can find it here: https://github.com/OBenned/DiscordSoundbot-Docker

@Darkside138 You are more than welcome to use it all on this repo and i can help you build it and push it to your own docker repo if you want

Related issue: https://github.com/Darkside138/DiscordSoundboard/issues/67

**Comment by Darkside138** [comment]
This is something I've wanted to do. If possible I could integrate the
docker config into the main repo. Just make a PR.

**Comment by Darkside138** [comment]
It's really ironic that you did this. I'm literally in a docker training
course right now. :) Glad you did though. Nice work.

**Comment by OBenned** [comment]
Sure thing, will make a PR soon, if you need any help with Docker i would be happy to help, doing this everyday :)

**Comment by OBenned** [comment]
There we go: #107
