### ISSUE TITLE
Removing successful commands

### ISSUE THREAD

**Issue by tchikboom** [Darkside138/DiscordSoundboard#11]
This is more a suggestion than a real issue, feel free to remove it if you think this is not the right place for it.

Before using your soundboard I was using [JMTK's Lopez bot](http://www.jmtk.co/#discordbot). I prefer your bot in many ways, but there is one feature that I miss from Lopez: after issuing a succesful soundboard command, the bot removed the message from the channel.

Do you think this is something you could implement in DiscordSoundboard? Thanks a lot for your time and your great bot.

**Comment by Darkside138** [comment]
This! I love this idea. I can definitely work on this. I'll update this issue when I have a new release ready.
