### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by heewphan** [Darkside138/DiscordSoundboard#110]
Hey man,

Been following your project for a while. It seems like you not only abandoned this one but pretty much all your projects from the looks at your activity. Hope all is well on your end.

**Comment by Darkside138** [comment]
Hey, I appreciate you reaching out. All is well here, I've just been very
busy with another project. If you're really interested you can check out
what I've been up to at cosmotronsgame.com or facebook.com/CosmotronsGame.

I haven't forgotten about this project and I still use the soundboard in my
discord almost every time I'm on. Like any other open source project I of
course welcome contributions if anyone else wants to add features or fix
bugs.

Again, thanks for reaching out. I appreciate it.

**Comment by oopsies49** [comment]
I've been playing around with my fork fairly regularly and added some new features. It diverged pretty significantly from the main repo because I wanted to play around with gradle and learn about it. The PR would be a pain to merge.

**Comment by Darkside138** [comment]
Hey, I've checked into the main branch. Feel free to pull down main and see if you can more easily merge in the features you added I'd be happy to review your PR.
