### ISSUE TITLE
Entrance for all

### ISSUE THREAD

**Issue by Manuel3115** [Darkside138/DiscordSoundboard#113]
Is there a way to set an entrance/disconnect sound that applies to all users ? For now I created a duplicate of my sound file for every user, but that takes a lot of space on my computer and clogs up the soundboard's localhost page. If this is not currently supported, it would be a great feature to add.

**Comment by Darkside138** [comment]
That is not currently supported but could be added. Honestly, I haven't
worked on the project much in the last couple of years but I'll add it to
the list.

**Comment by Manuel3115** [comment]
Alright thanks for the quick answer ! I'll try to use my limited java knowledge to hotfix the issue so it works with my server.

**Comment by Darkside138** [comment]
If you do you can always submit a PR after you've made the changes to
incorporate them for everyone.

**Comment by Manuel3115** [comment]
Is the github repo up to date ? When I cloned it, there were a couple of missing packages, notably something called dv8tion. I noticed I tried extracting the source code in the latest build and it's a bit different.

**Comment by daniel-san-fried** [comment]
> Is there a way to set an entrance/disconnect sound that applies to all users ? For now I created a duplicate of my sound file for every user, but that takes a lot of space on my computer and clogs up the soundboard's localhost page. If this is not currently supported, it would be a great feature to add.

I even don't get how to setup a entrance sound at all?! Can you pn me or something and explain it to me, please? :)

**Comment by daniel-san-fried** [comment]
So it is also not possible to have a different entrance and exit sound, right? @Manuel3115 or do you have a solution to this? We could get in touch if you want.

**Comment by Manuel3115** [comment]
Simply call the sound file the name of the user and that sound file will play when the user connects. For a leave sound, call the sound file the name of the user and then add a suffix at the end. By default that suffix is "_leave", but you can change it in app.properties.

**Comment by daniel-san-fried** [comment]
okay. i don't have that line in the app.proberties file hm... what do i have to add there?

**Comment by Manuel3115** [comment]
leave_suffix=_leave

Look for it... It should be there. If not, there's no point in adding it. It won't work. Your version is probably not up to date. Download the newest version and redo the basic setup

**Comment by daniel-san-fried** [comment]
Ok. I think I'll just leave it this way with the "_leave" command. According to the console it works. Will test it tonight with a friend. Thanks :)

**Comment by Cmeregirl** [comment]
Did anyone ever get an entrance sound for everyone working?

**Comment by Manuel3115** [comment]
No, I had issues when compiling the code as it currently is on github. My guess is that someone made some change and Darkside138 merged it with the main branch without realizing that it didn't compile.

**Comment by cnschu** [comment]
is this still an issue?

**Comment by Darkside138** [comment]
This feature still doesn't exist.

**Comment by Darkside138** [comment]
Added in the latest release 3.1.2
