### ISSUE TITLE
Edit what game bot is playing?

### ISSUE THREAD

**Issue by Cmeregirl** [Darkside138/DiscordSoundboard#116]
Hello, is it possible to edit what game the bot says it's playing?  ie "!help for a list of commands"
Or rather what file would I find that line in to edit?  Thanks in advance.

**Comment by Darkside138** [comment]
There currently is not. I could add this as on config in the properties file though

**Comment by Darkside138** [comment]
In the next version, set "activityString" in the properties file to configure this.
