### ISSUE TITLE
Leaving Sound

### ISSUE THREAD

**Issue by Jufoli** [Darkside138/DiscordSoundboard#12]
First of all, thanks for your work and this great bot!

I am using it a while now on my server and everyone added his/her own joining sound, we all love it! I have been asked if it's possible to also add a leaving sound. So if someone disconnect from a voice channel you have your own leaving sound.

Is it possible to add something like that? Like the event for leaving a channel triggers the bot to look for a sound like: "username+bye" and plays it?

Greetings,
Jen

**Comment by Darkside138** [comment]
It's certainly possible and wouldn't be a lot of work, I'll add it to the next release :)

**Comment by Darkside138** [comment]
Added in latest release.
