### ISSUE TITLE
Soundbot relogging repeatedly, won't play sounds

### ISSUE THREAD

**Issue by decordas** [Darkside138/DiscordSoundboard#122]
Hi, I've been using your discord bot for a few years now to play short mp3 clips in our voice channel. I started it up today and noticed to my surprise that the Soundbot kept joining & leaving the voice channel repeatedly. It also wouldn't actually play any sounds. This setup (and the sounds I tried) are all things that have worked fine in the past, so I was just wondering if you knew what might have caused this - thanks!

I noticed when I download the files again the files are completely different (something called "gradle" which I don't have in my old Soundbot directory?) -- if something has changed and I need to DL the new files and set them up again, that's fine, just looking for confirmation.

**Comment by SimonLandmine** [comment]
Same issue found here. Again, please confirm whether a reinstall is required!

**Comment by Darkside138** [comment]
Yes, you need the latest version. The old version does not work any more
due to changes in the Discord API.

**Comment by SimonLandmine** [comment]
Ah! Thanks. Darned non-backward-compatible APIs!
Thanks for all of your work on this!

**Comment by L4wlz** [comment]
i'm having the same issue but with the docker version it just keeps connecting and disconeccting :(

**Comment by SimonLandmine** [comment]
When does your install date from? As @Darkside138 mentioned, there was an API change which required a rebuild, so it might be worth trying a reinstall - I had exactly the same symptoms, and installing the latest version did the job.

**Comment by L4wlz** [comment]
I have been using this docker from dockerhub.. https://hub.docker.com/r/obenned/discordsoundbot
Maybe that one is outdated :(

**Comment by L4wlz** [comment]
I can see it downloads this version : DiscordSoundboard-2.2.2-beta.tar hmm but the newest is 3.0.4 but  there is no tar version ? @Darkside138 will there be a newer docker version ?

**Comment by Darkside138** [comment]
Yes you need the latest. That old version won't work any more.

The new zip file should work fine on docker. No need for a tar.

**Comment by OBenned** [comment]
I've updated the docker image, so you should be able to use it again.
The image have been pushed to docker hub
