### ISSUE TITLE
Adding entrance sound for users with a space in their name.

### ISSUE THREAD

**Issue by yorcadon** [Darkside138/DiscordSoundboard#126]
I'm not able to add an ?entrance for users that have a space in their discord name. I cannot figure out how to use their user ID either, I've tried just the number by itself, with @userID and with <@userID> but none seem to work. Is it possible to manually add it into a file somewhere on the machine running the bot?

**Comment by bobotran** [comment]
I had difficulties with this as well. But you can follow the instructions at this link [https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-](url) to discover someone's Discord ID. From that, the ?entrance command should work fine.

**Comment by hippotread** [comment]
Has anyone figured out how to set entrance sounds with files that have spaces?

**Comment by Darkside138** [comment]
Use the latest version 3.2.1 and add based on their discord ID and it will work.
