### ISSUE TITLE
Suggestions!

### ISSUE THREAD

**Issue by ndo360** [Darkside138/DiscordSoundboard#129]
Greetings, I have a couple of suggestions that I think would be amazing for this app.

1) Restoration of the 'Stop Sound' button.
This button was amazing, and allowed for the sound sounds quickly without typing a command. I believe it has been removed.
2) Folders to organize sounds.
This would help keeping things like 'Sound Effects' and 'Background Music' separated.

Hopefully these will be possible in a future update!

**Comment by Darkside138** [comment]
Yeah, honestly I'm not sure where the stop button went. I can look into
that.

You can do folders now. The folders will each be a category on the UI and
then you can filter by category.

Hope that helps!

**Comment by ndo360** [comment]
Thanks for the reply! Also something I neglected to mention is that I would love the ability to loop sound effects.

The looping sound effects would be for background ambiance, and the sort. Maybe a little 'tickbox' thing that a user can click to tell the program that they want that endlessly looping until the sound is manually stopped.

This could allow for multiple sounds like rain, windshield wipers, and the sort be played over and over for a scene in a discord call.

If that is already in the latest version, then awesome! I just don't recall that being a feature.

**Comment by SimonLandmine** [comment]
Another vote for looping here - I use Soundboard to play TableTopAudio's ambience pieces when running TTRPG over Discord (as well as for providing sound effects), and it's very handy!

**Comment by snelson2342** [comment]
Another vote for fixing the stop button

**Comment by Darkside138** [comment]
Stop button works in the new UI. Repeat is on the list just have very limited time.

**Comment by SimonLandmine** [comment]
No worries - and thanks for all of your work on this! Without it, my campaign wouldn't have the custom theme tune that's helped build player immersion.
