### ISSUE TITLE
JDA Error

### ISSUE THREAD

**Issue by SamuelGTurner** [Darkside138/DiscordSoundboard#13]
Nov 01 22:14:52 raspberrypi java[4268]: [22:14:52] [Warning] [JDASocket]: Got an unexpected Json-parse error. Please redirect following message to the devs:
Nov 01 22:14:52 raspberrypi java[4268]: JSONObject["endpoint"] not a string.

**Comment by Darkside138** [comment]
Not sure what's going on here. Never tried running on a raspberryPi though. What version of java is it running? You must have java 8 installed for it to work.

**Comment by SamuelGTurner** [comment]
I'm running the following Java version:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

It runs great on my Pi, there was no obvious issue at the time this message logged, I just noticed it when adding some new sounds and posted it as it said message the devs. Thought it might've been something you were tracking :)

**Comment by Darkside138** [comment]
That error seems to be coming from the JDA lib.
