### ISSUE TITLE
How to play URLs?

### ISSUE THREAD

**Issue by ndo360** [Darkside138/DiscordSoundboard#131]
I tried to play some videos from YouTube... but there is no command listed that explains how it works... how do I get videos to play?

**Comment by Darkside138** [comment]
?url httpsLinkToTheVideo

**Comment by ChiffX** [comment]
Is it possible for soundbot to delete the chat post after commencing the audio? Similar to locally-hosted files

**Comment by Darkside138** [comment]
Yeah, it could. Just need to add the code to do so. I'll add it to the list.

**Comment by Darkside138** [comment]
Added
