### ISSUE TITLE
No way to remove entrance sounds for users?

### ISSUE THREAD

**Issue by hbrakes** [Darkside138/DiscordSoundboard#136]
Is there any command or method to remove entrance sounds for users? Even switching my name in discord doesn't clear my 'intro'.

**Comment by raitono** [comment]
I found that you can leave off the sound name to clear it. Doing `?entrance userName` in a text channel will clear the entrance sound. Works similarly for leaving with `?leave userName`

**Comment by Darkside138** [comment]
Above works. I've also updated the help command to note this.
