### ISSUE TITLE
Some files cut short a second or so. 

### ISSUE THREAD

**Issue by jusplainmike** [Darkside138/DiscordSoundboard#137]
I am using the latest beta version of the bot, following the github for install. A bunch of my audio files cut short a second or so. I can confirm its not my audio clips as I am using file from my previous bot and I manually checked them on my pc using VLC. Is anyone else having this issue and if so was there any way to fix? There is no error being thrown so I am not sure what is causing this.

**Comment by Darkside138** [comment]
I've heard of one other person with this issue. Not sure if they were able
to resolve it. I can't seem to reproduce. Can you give me some more
information about your system, please? OS, CPU (AMD, Intel), Java version,
etc.

**Comment by jusplainmike** [comment]
`Linux narphaven 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

`openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)`


`michael@narphaven:~$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:            4
CPU MHz:             2294.608
BogoMIPS:            4589.21
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 pku ospke md_clear`

**Comment by Darkside138** [comment]
This is what I'm currently running by servers bot on:

Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-51-generic x86_64)

openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed
mode, sharing)

**Comment by jusplainmike** [comment]
I will try a different version of java and report back.

**Comment by bardyspoon** [comment]
I was seeing this issue with some files in my bot, but it seems to be fixed following the recent dependency updates.

**Comment by Darkside138** [comment]
Thanks again bardy for updating those dependencies and testing!
