### ISSUE TITLE
Audio volume does not change. [WIP]

### ISSUE THREAD

**Issue by jusplainmike** [Darkside138/DiscordSoundboard#138]
Using the webui or the chat commands does not change the volume. I looked through the closed issues and others have had the same issue but they were closed out without any update. Again no error is being shown so I am not sure what may be wrong. I am using the setup guide from the github with the recommended version of node.

**Comment by Darkside138** [comment]
I believe the latest refactor broke the volume. I want to say that someone
may have fixed it and I just need to make a new release with the latest
code. I'll check and if so get a new release out.

**Comment by jusplainmike** [comment]
Thanks buddy, we love your bot its something we've been looking for in my discord server for a long time.

**Comment by Darkside138** [comment]
I believe this is fixed with the latest. Works through the UI for me.
