### ISSUE TITLE
soundplayerImpl token is not valid 

### ISSUE THREAD

**Issue by Rasphodos** [Darkside138/DiscordSoundboard#15]
Hy for first i want you say thank you for you job but i have a problem. I see the tuto video but when i want to start the bot i have this message and i don't undersand why :/ Can you help me please ?

**Comment by Darkside138** [comment]
Sounds like you need to make sure your bot token is correct in the app.properties file. 

bot_token=BUNCHOFLETTERSWITHSOME.PERIODSAND.SOME_UNSDERSCORES

Something like that above. You would get that token from the discordapp website.
