### ISSUE TITLE
Stop Button Still Missing

### ISSUE THREAD

**Issue by ndo360** [Darkside138/DiscordSoundboard#151]
Downloaded the latest version and noticed a few missing things.

1) The Stop Button still missing on the GUI

2) The latest version doesn't have the application properties file?

**Comment by cnschu** [comment]
to improvise a stop button, simply make a "stop" file, with like 0.25 seconds of silence in it. If you press the button created in the interface for this file, it will stop the current playback.

**Comment by cnschu** [comment]
i've updated the readme to reflect the missing config file in the release.

**Comment by cnschu** [comment]
3.0.6 comes with a config, issue can be closed

**Comment by cnschu** [comment]
in 3.0.6. there is a config included and a stop-button in the web interface.
@Darkside138 please resolve/close this issue
