### ISSUE TITLE
Release 3.0.5: bot doesn't listen to other bots / webhooks

### ISSUE THREAD

**Issue by cnschu** [Darkside138/DiscordSoundboard#157]
**how it is:**
if a bot / webhook posts an command, the soundboard don't react to it.

**how it should be:**
To control the soundboard with an actual soundboard (like a stream deck) 
a) it has to accept commands from webhooks.
AND / OR
b) a direct URL on http://localhost:8080/... could be provided for control by HTTP request

**Comment by Darkside138** [comment]
The bot does operate through REST requests. It could be controlled that way. Not sure how to allow the bot to accept commands from webhooks. I can look into it.

**Comment by cnschu** [comment]
the problem with the REST request ist, that it doesn't accept the name of the file, but an ID.

**Comment by Darkside138** [comment]
The ID is the name of the file minus extension.
