### ISSUE TITLE
Soundboard keeps crashing on startup (CentOs server)

### ISSUE THREAD

**Issue by 1vadios** [Darkside138/DiscordSoundboard#16]
Trying to set up the board on a centos server, and let it run there but on startup, it gets killed all the time.
Output:

> $ java -jar DiscordSoundboard.jar net.dirtydeeds.discordsoundboard.MainController
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/zeus/SoundBoard_Cobalt/DiscordSoundboard.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/zeus/SoundBoard_Cobalt/DiscordSoundboard.jar!/lib/logback-classic-1.1.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

 

>  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v1.4.6)

> 2016-11-09 13:13:57.777  INFO 13654 --- [           main] n.d.discordsoundboard.MainController     : Starting MainController v1.4.6 on osiris with PID 13654 (/home/zeus/SoundBoard_Cobalt/DiscordSoundboard.jar started by zeus in /home/zeus/SoundBoard_Cobalt)

> 2016-11-09 13:13:57.781  INFO 13654 --- [           main] n.d.discordsoundboard.MainController     : No active profile set, falling back to default profiles: default

> 2016-11-09 13:13:59.414  INFO 13654 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4471dd00: startup date [Wed Nov 09 13:13:59 UTC 2016]; root of context hierarchy

> 2016-11-09 13:14:22.380  INFO 13654 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]

> 2016-11-09 13:14:27.287  INFO 13654 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring

> 2016-11-09 13:14:28.529  INFO 13654 --- [           main] o.s.s.a.AsyncAnnotationBeanPostProcessor : No TaskExecutor bean found for async annotation processing.

> 2016-11-09 13:14:30.613  INFO 13654 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$811c7926] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

> 2016-11-09 13:14:41.688  INFO 13654 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)

> 2016-11-09 13:14:41.835  INFO 13654 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat

> 2016-11-09 13:14:41.843  INFO 13654 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.32

> 2016-11-09 13:14:43.762  INFO 13654 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext

> 2016-11-09 13:14:43.762  INFO 13654 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 44645 ms

> 2016-11-09 13:14:50.774  INFO 13654 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]

> 2016-11-09 13:14:50.901  INFO 13654 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]

> 2016-11-09 13:14:50.912  INFO 13654 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]

> 2016-11-09 13:14:50.920  INFO 13654 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]

> 2016-11-09 13:14:50.921  INFO 13654 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]

> 2016-11-09 13:14:51.725  INFO 13654 --- [ost-startStop-1] o.a.c.util.SessionIdGeneratorBase        : Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [502] milliseconds.

> 2016-11-09 13:14:57.341  INFO 13654 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'

> 2016-11-09 13:14:57.499  INFO 13654 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
>         name: default
>         ...]

> 2016-11-09 13:14:58.597  INFO 13654 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {4.3.11.Final}

> 2016-11-09 13:14:58.615  INFO 13654 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found

> 2016-11-09 13:14:58.624  INFO 13654 --- [           main] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist

> Killed

**Comment by Darkside138** [comment]
I  don't see anything in that stack trace that's obvious. All seems pretty normal, then it just kills.

What version of java do you have?

**Comment by 1vadios** [comment]
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by Darkside138** [comment]
I'm not really sure what's going on. It's going to take a bit of investigation.
