### ISSUE TITLE
Can we get the docker updated to latets version ? 

### ISSUE THREAD

**Issue by L4wlz** [Darkside138/DiscordSoundboard#160]
https://hub.docker.com/r/obenned/discordsoundbot is still version 3.0.4 ? can't this somehow be alligned so it always will have the new version ? :)

**Comment by cnschu** [comment]
have you talked to the owner of this docker repository?

**Comment by L4wlz** [comment]
It just looks like the support was pointed over here.  I can try tag him.
@OBenned - Can you please update the docker on the https://hub.docker.com/r/obenned/discordsoundbot so it can get the newest version.. I tried to do a fresh install and i still get the old version 3.0.4 ?

**Comment by Darkside138** [comment]
I'm no docker expert but the dockerfile seems to be pointed at the latest release. 

`RUN wget $(curl -sL https://api.github.com/repos/Darkside138/DiscordSoundboard/releases/latest | jq -r '.assets[].browser_download_url')`

I would think a fresh install would get the latest version.

**Comment by L4wlz** [comment]
I have done a fresh install of the bot before posting here :) but the version is still 3.0.4 :( - 

But i can give it a try again for sure

**Comment by L4wlz** [comment]
I just did a complete reinstall of the docker from the dockerhub. :)
- So remove my container and all it contents.
- Removed images and a clean up everything. 
But it still gives me
![image](https://user-images.githubusercontent.com/62191448/104138519-dd736000-53a4-11eb-8025-6d61e3237d8e.png)
Normally i can via portainer just edit current container and then check **Always pull the image** and then redeploy- works just fine with other dockers :) So i'm pretty lost here :S

**Comment by OBenned** [comment]
When i try and down the ZIP file using the command the docker image uses i get the latest version, timestampe 5. january 2021
![image](https://user-images.githubusercontent.com/1587311/104161242-cbb8a980-53f2-11eb-907f-efd79ade0763.png)

I havent tried the image yet, but i will give a shot

**Comment by OBenned** [comment]
I have found the issue.

The problem is, cause of my own mistake, when i build the image it pulls the latest version, and when the image was last build was in version 3.0.4.
So the zip is not pulled during the startup of the container but when i build the image.

So there are two possible solutions.

1. The docker image has to rebuild with every new version.
2. The docker image needs to be redesigned so it can handle this instead of rebuild, i dont have the time for this solution atm.

I have rebuild and pushed the newest version to docker hub now.

@Darkside138 Tell me what solution you would prefer

**Comment by L4wlz** [comment]
@OBenned Thanks.. I have just rebuild it and now it is the latest version. 
But yeah solution 2 will be best :D but the time needs to be there..

**Comment by OBenned** [comment]
The 2 version is actually the worst because everytime you start the container you need to pull the latest release, unless we do some fancy check on releases.
The good thing about how its done now, is that we "bake" the image with the latets release, so imo more safe doing it this way

**Comment by Darkside138** [comment]
@OBenned, I'm about to push a new release. I wouldn't mind setting up some kind of build chain. Let me know if you want to work together on it.

**Comment by OBenned** [comment]
@Darkside138 For sure, im up for that!
