### ISSUE TITLE
Error creating bean with name 'soundPlayerImpl'

### ISSUE THREAD

**Issue by Akbadain29** [Darkside138/DiscordSoundboard#162]
I have downloaded latest (3.0.6) from the README.md link and I am on Windows 10. The bot does appear on the server and displays its activity string when I run the .bat. However, I get the same error message as #134 and I don't know why. 

I ran the soundboard in debug mode and have attached the result (including the Conditions Evaluation Report) in case that helps.
[soundboard_debug_information.txt](https://github.com/Darkside138/DiscordSoundboard/files/5861602/soundboard_debug_information.txt)

**Comment by Darkside138** [comment]
This may be cause by using a 32 bit version of Java. Make sure you have 64bit Java installed.

**Comment by hippotread** [comment]
I had the same issue, but with 64bit Java 8 on Ubuntu. Figured out that it was caused by a file without the mp3 extension in the sounds directory.

**Comment by clement-or** [comment]
Same error here on Windows 10 with Java 1.8 64-bits

**Comment by Darkside138** [comment]
Better error handling added for when bot token is missing in 3.1.0. The release will be uploaded shortly.
