### ISSUE TITLE
Bot crashes on startup

### ISSUE THREAD

**Issue by daniel-san-fried** [Darkside138/DiscordSoundboard#171]
The bot doesn't start anymore (I changed nothing, it just happened).

Console says "Failed to initialize jpa entitymanagerfactory". I have Java 17+ 64bit installed. I changed nothing in the config, it just went offline on my second PC and won't start again. Any Idea where to look first?
![error](https://user-images.githubusercontent.com/35974595/168467347-8e646eb9-1ff8-4359-b1e6-cae88649d0e7.JPG)

**Comment by ndo360** [comment]
The issue is that the database line is out of date within the appliciation.properties file.

It should read as: 
`spring.datasource.url=jdbc:h2:file:./discordDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE`

**Comment by daniel-san-fried** [comment]
> The issue is that the database line is out of date within the appliciation.properties file.
> 
> It should read as: `spring.datasource.url=jdbc:h2:file:./discordDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE`

Dude! You freaking nailed it, thanks! I asked everywhere and you helped me a lot. Thank you so much :) Have a great week.

**Comment by lbrayner** [comment]
@Darkside138 Please consider changing `spring.datasource.url` in `application.properties` (bundled in the release) to either `jdbc:h2:file:./discordDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE` or `jdbc:h2:mem:discordDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE`.
