### ISSUE TITLE
Can't read input file!

### ISSUE THREAD

**Issue by JulioBBL** [Darkside138/DiscordSoundboard#19]
i just configured the bot on my raspberry pi, followed the video tutorial closely, but when i run the bot, it doesn't get online in the discord room, what could be the problem?

looking through the logs, i got a warning saying that it doulnd't find the app.properties file, but i haven't changed it's directory.
i get an exception on java, but is a imageio.IIOException, can it relate to my problem?

**Comment by Darkside138** [comment]
No that is just the bot looking for an image to use as it's avatar in discord. That should not stop it from working. Does the bot respond to commands at all?

**Comment by JulioBBL** [comment]
Nope, it dosn't even get connected to the discord server/room

**Comment by Darkside138** [comment]
Closing due to major new release. This is for the old version.
