### ISSUE TITLE
Some sound files are not playable.

### ISSUE THREAD

**Issue by LKarzon** [Darkside138/DiscordSoundboard#20]
When playing sound files, some of them do not work when played over discord and they just sound like fingernails on a chalkboard. Others work fine. I don't see a pattern in the ones that do and don't though.

**Comment by z1g** [comment]
Sounds like what happens when you try to use mono files with JDAPlayer. Check to see if they are mono and if they are convert to stereo.

**Comment by LKarzon** [comment]
Yea, that fixed it. Thank you. What other players are there instead of converting every file? 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: z1g <notifications@github.com> Date: 11/29/16  20:06  (GMT-06:00) To: Darkside138/DiscordSoundboard <DiscordSoundboard@noreply.github.com> Cc: LKarzon <leith.karzon@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [Darkside138/DiscordSoundboard] Some sound files are not
  playable. (#20) 
Sounds like what happens when you try to use mono files with JDAPlayer. Check to see if they are mono and if they are convert to stereo.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Darkside138/DiscordSoundboard","title":"Darkside138/DiscordSoundboard","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Darkside138/DiscordSoundboard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@z1g in #20: Sounds like what happens when you try to use mono files with JDAPlayer. Check to see if they are mono and if they are convert to stereo."}],"action":{"name":"View Issue","url":"https://github.com/Darkside138/DiscordSoundboard/issues/20#issuecomment-263761311"}}}

**Comment by Darkside138** [comment]
You can configure the player in the app.properties file (player=JDAPlayer). The valid options are musicPlayer or JDAPlayer.
