### ISSUE TITLE
Not removing issued commands

### ISSUE THREAD

**Issue by z1g** [Darkside138/DiscordSoundboard#26]
Not sure what happened, I suspect a change on the discord side, but the bot is no longer removing the commands once issued.  The permissions are set correctly, it has worked since the change was implemented  but sometime today it stopped working? Anybody else seeing this?

**Comment by Darkside138** [comment]
Is there any error when this happens? It's still working for me but I may be running a slightly older version of the bot.

**Comment by z1g** [comment]
There is no console error.  If I remove the manage messages permission from the bots role then it will output the permissions error in the console which you would expect:

net.dv8tion.jda.exceptions.PermissionException: Cannot preform action due to a lack of Permission. Missing permission: MESSAGE_MANAGE

This would indicate that the bot is trying to remove the message however when the bot has the manage messages permission there is no error, you can see the Attempting to play file info and that is it.

This started for me after changing the server location from US West to US Central.

**Comment by Darkside138** [comment]
I'm hoping the latest release fixes this issue for you (1.4.9). Please update and open a new issue if your still having problems.
