### ISSUE TITLE
Not responding to ?list command

### ISSUE THREAD

**Issue by z1g** [Darkside138/DiscordSoundboard#27]
I suspect something has changed on the discord side, however as of yesterday I am getting an error when issuing the list command.

Mac OSX Java 1.8.0_111
[ChatListener]: Responding to list command. Requested by Chicken.
[14:56:24] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[14:56:24] [Fatal] [JDA]: Encountered an exception:
[14:56:24] [Fatal] [JDA]: net.dv8tion.jda.exceptions.BlockedException: The requested User blocks you or disallows you otherwise from PMing him!

Windows 10 Java 1.8.0_111
[14:54:37] [Info] [ChatListener]: Responding to list command. Requested by Chicken.
[14:54:37] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[14:54:37] [Fatal] [JDA]: Encountered an exception:
[14:54:37] [Fatal] [JDA]: java.lang.RuntimeException: Could not get Private-channel for user: Chicken... Error: HTTPResponse[401: {"code": 0, "message": "401: Unauthorized"}]

I setup a new instance on windows 10 today with a freshly downloaded bot, created a new discord user, discord server, and discord app for the bot. The bot will play all of the sound files without issue and adjust volume.  I gives the above error to the list command and will not remove previously entered commands. The bot does have manage message permissions and does throw an error when I remove that permission but shows no console error otherwise.

I have made absolutely certain the bot is not on the block list for my test user.  I am not sure why the error is different between the two platforms. This started yesterday, was working perfectly well prior to.  I imagine discord changed something on their back end, not sure.

**Comment by RyanBlue** [comment]
I'm also having this issue. Not sure whats the cause.

**Comment by Darkside138** [comment]
If I'm reading your error correctly the bot is trying to send the list of sounds to a user named "Chicken". That user is blocking private messages from either the bot user or all users. Not sure where you can see a list of users that are blocked in discord, but I would check there first.

**Comment by z1g** [comment]
You can view blocked users by clicking the online button in the top left corner then click the blocked tab.  I have no blocked users on that account as it is brand new.  Additionally the error occurs for all users that issue the list command. Oddly as I mentioned the error is different from mac/nix to windows.

![blocked](https://cloud.githubusercontent.com/assets/23297776/21352669/caeffc88-c67f-11e6-89f7-5c8e5f333814.png)

**Comment by z1g** [comment]
#30 duplicate but relevant

**Comment by Darkside138** [comment]
I have a release being uploaded right now that will fix this issue. v1.4.9. Please update to that and if your still having issues open a new ticket.
