### ISSUE TITLE
Bot will ignore command from a single user

### ISSUE THREAD

**Issue by seriousmillz** [Darkside138/DiscordSoundboard#32]
I have someone that no matter what command they use the bot just ignores it. [?]help doesn't get a response either. Everyone else can use the bot just fine

**Comment by Darkside138** [comment]
Check your app.properties file. Do you have anyone configured as a bannedUser?

**Comment by seriousmillz** [comment]
Nope, I even tried deleting the example names that were there. I just upgraded to a more recent version of the bot.
