### ISSUE TITLE
adding sounds via filetransfer not working

### ISSUE THREAD

**Issue by madMonKAY** [Darkside138/DiscordSoundboard#34]
This feature worked on 1.4.8 and stopped working in 1.4.9 it still doesn't work in 1.4.10 sadly as it is the most used feature by my users.
Adding sounds manually still possible.
The log shows no entry at all for file transfers so I'm not 100% sure how to provide you with more information but if you need something just ask.

**Comment by z1g** [comment]
Not a dev, but just curious.  When you say adding via file transfer exactly how are you doing this? Again, just curious.

**Comment by Darkside138** [comment]
He's referring to the feature where you can attach a file in a pm to the
bot. The bot takes the file and adds it to the sound board.

**Comment by z1g** [comment]
Thanks, I did not know that was possible.

**Comment by Darkside138** [comment]
Looks like discord changed the way files upload to a direct message. I'm no longer getting an Message Received event to know the user sent the file. I'm planning a fairly large re-write to update the unlying library I'm using. Hopefully, that will help fix this issue.

**Comment by Darkside138** [comment]
This is fixed in the latest BETA
