### ISSUE TITLE
Bot enters channel, does nothing, then leaves

### ISSUE THREAD

**Issue by Feldrius** [Darkside138/DiscordSoundboard#35]
Title. 

The console does not show any errors when I enter the command, so I don't really know what's up. Any help would be appreciated.

**Comment by Feldrius** [comment]
Fixed it by accessing localhost:8080 and playing a sound there.

**Comment by z1g** [comment]
Two things that have worked for me to resolve the same behaviour:

1:) Open the web UI at http://localhost:8080 and click a button to play a sound file with a user selected from the dropdown box in the channel you want the sound to be played

2:) Change the server location in the Discord server settings.

**Comment by TehDonut** [comment]
I'm also getting this issue... The main use case for our discord server is people want to use the chat commands for the bot to come in, play the sound, then leave. The web interface causes the bot to join, play the sound, then remain in the channel. The chat command causes the bot to join the channel, do nothing, and then leave. I'm not getting any error messages in the console so I have no idea what's going on. 
Would definitely appreciate some help. Thanks.

**Comment by z1g** [comment]
Not a Dev, just a user who uses the bot. Do you use the bot to connect to multiple servers or just one?

**Comment by TehDonut** [comment]
Just one

**Comment by Kingspian** [comment]
Same here. Im using 2 servers and when I tried to get the bot to play a sound effect using mp3 on another server. The bot just shows up then leaves. No sounds.

**Comment by Kingspian** [comment]
Yea it does that to me too. Kind sucks. Im sure Darkside will make it happen one day. It still needs more work ;)

**Comment by Darkside138** [comment]
Yeah, one of these days I'll have some free time :(

Sorry guys, it's something I've been meaning to get to.

**Comment by Kingspian** [comment]
Thats no big deal. :). I've managed to open another Bot Temporarily untill you have time to fix it. It's all good :)

**Comment by Darkside138** [comment]
This works better now in the BETA version
