### ISSUE TITLE
Bot takes a long time to start up

### ISSUE THREAD

**Issue by samuscherer** [Darkside138/DiscordSoundboard#36]
I'm running the bot on a Debian 8.6 virtual machine and it takes ages to start up, at least 5 minutes. Do you have any idea what could cause this behaviour?

**Comment by GrandpaLemon** [comment]
I've the same problem using the Oracle JRE (under Linux) in VirtualBox 4.3.40.

**Comment by samuscherer** [comment]
I solved the problem, it was caused by VirtualBox. KVM works perfectly fine.
