### ISSUE TITLE
Allowing all users no longer working

### ISSUE THREAD

**Issue by Pandabrain** [Darkside138/DiscordSoundboard#38]
allowedUsers in app.properties no longer works for all users if the list is empty.
If the list is empty, the bot only responds with "I don't take orders from you."

**Comment by z1g** [comment]
Latest release should resolve that issue:

https://github.com/Darkside138/DiscordSoundboard/releases/tag/v1.4.11

**Comment by Pandabrain** [comment]
Thanks, didn't see that, the README.md on the landing page still lists and links v1.4.9 as the latest version.

**Comment by Darkside138** [comment]
Yeah, I need to update that. I also have a beta release I need to get out
too. 😉
