### ISSUE TITLE
Help Needed: "I don't take orders from you"

### ISSUE THREAD

**Issue by Sythalin** [Darkside138/DiscordSoundboard#42]
Fresh install, every user gets this no matter what command they type in via Discord chat.  The command window says "[Warning][ChatListener]: Unable to delete message"

I've tried reinstalling several times, all ends up the same.

ver: 1.4.9

**Comment by z1g** [comment]
The bot needs manage messages permissions.

**Comment by Darkside138** [comment]
z1g, you rock. Thanks for all the help answering questions.

**Comment by Sythalin** [comment]
That solves for the bot removing "invalid" commands from chat, but it's still whispering back "I don't take orders from you." on every chat command.  I've tried creating a role that grants every permission and assigned it to the bot, with no change.

**Comment by Darkside138** [comment]
Remove the line in the app.properties that is allowedUsers =

**Comment by Darkside138** [comment]
Or make sure your on the latest version 1.4.11

**Comment by Sythalin** [comment]
Upgrading to 1.4.11 seems to have fixed it.  Just FYI, main page still lists 1.4.9 as latest.  Thanks!

**Comment by Darkside138** [comment]
Yeah I need to update.
