### ISSUE TITLE
Set what the bots playing

### ISSUE THREAD

**Issue by Jutebox** [Darkside138/DiscordSoundboard#44]
Not really a issue but I unpacked the "discordsoundboard.jar" to change the "Playing Type !help for a list of commands." line but not sure where to look and there are tons of files/folders. Was wondering if you could point me in the right direction.  Please and thank you.

**Comment by Darkside138** [comment]
That is currently in the java code. I plan to make it more configurable in
the future but currently it is not. If you were determined you could
download the source from GitHub, change the text, and build the project.

**Comment by Jutebox** [comment]
Earlier I cloned the bot to make it a sorta music bot. I was originally using rhino for that but discord, bad code and bitrate were messing with it so much that it was more of a pain to even host, and my connection is 1gb up+down. I ended up configuring yours for a music bot and it works great. That aside ill just wait for you to update the options in whenever. 

Also when you do get around to updating this, if its not any extra work or to much trouble you could add a autoplay feature and this would be one sick music bot but yea thanks for the help and look forward to future updates!

**Comment by Darkside138** [comment]
I've got a re-work in the works now. If your feeling into it your more than
welcome to incorporate your changes into that new branch and submit a PR.

**Comment by Jutebox** [comment]
Well honestly I would but I don't think its anything anyone would download but it does work for me like a charm, also found the file and built it back up. Thanks for the help ;D
