### ISSUE TITLE
Permiossions for use not working

### ISSUE THREAD

**Issue by sycoinc** [Darkside138/DiscordSoundboard#45]
I have set my username on discord to be the only one able to issue the commands but it seems to allow anyone in the server to issue the commands. Is there a fix for this or al;ternate setup

currently have `allowedUsers=myname`

**Comment by Pandabrain** [comment]
As a workaround i suggest using version 1.4.9.
Leaving the list empty doesn't work in that version, but setting allowedUsers does.
