### ISSUE TITLE
Is it possible to feed the Bot Youtube links?

### ISSUE THREAD

**Issue by Tr1n1ty1** [Darkside138/DiscordSoundboard#48]
Since the Discord File Transfer doesn't seem to work anymore woud it be possible to just use YT Links? 
the youtube-dl seems to be included anyway...

**Comment by Darkside138** [comment]
Not currently, I'm working on a re-work that should make it able to do so.

**Comment by ruvort** [comment]
Any progress on this?

**Comment by Darkside138** [comment]
There is a beta version available that does play URL links.
