### ISSUE TITLE
Bot Randomly Stops Playing Sounds After Awhile

### ISSUE THREAD

**Issue by Timtempor** [Darkside138/DiscordSoundboard#49]
I've been having this issue for the past couple weeks. I transferred the bot over to a dedicated AWS Windows 2016 Server. When I did this  I updated to the newest build and ever since then the bot will stop being able to play clips after a seemingly random amount of time. I can't seem to find a cause for the bug, there are no errors. All that happens is the bot tries to play a  clip, joins the channel, plays nothing and then leaves. Also we usually leave the bot sitting in the channel if that matters. 

When this happens the only thing that I can do to fix it is restart the bot until it works again.

**Comment by Darkside138** [comment]
Are any errors logged?

**Comment by Timtempor** [comment]
There are no errors logged. The only other info I have is that yesterday the bot wouldn't work at all. It was the same problem but it would happen immediately upon starting the bot, not even one clip would play. I was thinking... what change might have caused this. I remembered that in the newest version you added the disconnect clips. So I changed that string in the config file to blank. The bot started to work again, it has messed up only once since then. Don't know if it was just a coincidence or not but hope that helps.

**Comment by Darkside138** [comment]
Oh, that's really good info. I haven't got a chance to do very thorough
testing of all the different configs and that is certainly one I haven't
tried. I'll do some more testing around that. Thanks.

**Comment by Timtempor** [comment]
The only other thing I am thinking is that it might have something to do with the fact that the bot no longer joins my AFK channel. It used to follow users wherever they wen't, now it isn't able to join that room. I don't think anything changed in my server so I figured that was a change on the bot side.
Maybe when trying to play clips in a channel it can't access it messes everything up.

**Comment by Darkside138** [comment]
Going to close since the bot has been re-written with a new lib. Hoepfully that fixed it
