### ISSUE TITLE
Improvements and a Discord to try out stuff. 

### ISSUE THREAD

**Issue by theZasa** [Darkside138/DiscordSoundboard#5]
Hey Darkside. 
Great work with the bot. I use it myself and made some changes although I am very unfamiliar with Github. Would you like to review some of the changes, which I suggest? If so,  you can invite me to some Discord of yours and we can chat easier. 
Regards Zasa

**Comment by Darkside138** [comment]
Yeah, we could do that. I have a discord server you can join with this link: https://discord.gg/0J4pr2UNVqpolj6z.
