### ISSUE TITLE
Could you make an online version of the bot ^^

### ISSUE THREAD

**Issue by Highom** [Darkside138/DiscordSoundboard#50]
thought it would be cool to have the bot 24/7 avaiable for all people :D would it be possible for you to make this ❓

**Comment by GmCity** [comment]
unless there are restrictions built in then it would be a mess of weird audio clips after a short while,

**Comment by Darkside138** [comment]
Yeah, I don't want to make a bot available to everyone. Each person should run their own bot. It's possible to buy hosting and put the bot there.
