### ISSUE TITLE
Bot keeps getting Killed on Startup

### ISSUE THREAD

**Issue by Jpesky** [Darkside138/DiscordSoundboard#51]
I've seen this error listed in some other issues, but I'm not sure if it has been resolved yet. To be honest I'm not 100% sure I have installed JDA correctly (if at all). I am attempting to run this on an Ubuntu server. Any help would be greatly appreciated.

**Comment by Darkside138** [comment]
I would need to see the logs to have any insight.

**Comment by Jpesky** [comment]
@Darkside138 I quickly uploaded it to [paste bin](http://pastebin.com/hDDF91Q4) to make it a _tad_ bit more readable.

**Comment by Darkside138** [comment]
What version of java are you running (Needs to be Java 8)? Have you had
older versions running on this same Ubuntu server?

**Comment by Jpesky** [comment]
Yep, running Java 8. Maybe I didn't set up JDA?

**Comment by Darkside138** [comment]
All the JDA dependencies should be included in the soundboard jar. I'll try
to reproduce the issue and see what I can find.

**Comment by Jpesky** [comment]
Alright, thanks for the help. I've been messing around with it for the past hour with no avail.

**Comment by Darkside138** [comment]
Can you send me your app.properties file? It just dawned on me, that's
probably the best place to start.  Take your bot token out before sending.
