### ISSUE TITLE
Entrance/disconnect Listener

### ISSUE THREAD

**Issue by Firidan** [Darkside138/DiscordSoundboard#57]
Hey I managed to make bot use soundfile for user entrance (just file with their name) but I have no idea how should I name file for disconnecting users.

**Comment by GmCity** [comment]
In properties file there is a line "leave_suffix="  Put after that what you want the suffix to be.

For example if you wanted to amend "_leave" after your user then the line would be "leave_suffix=_leave" and the audio file (if mp3) would be "Firidan_leave.mp3"
