### ISSUE TITLE
2.0.1 version is not repeating 

### ISSUE THREAD

**Issue by Scahry** [Darkside138/DiscordSoundboard#58]
i'm currently using the 2.0.1 BETA version which even though it states to repeat the file x times only plays it one time and stops.
![unbenannt](https://cloud.githubusercontent.com/assets/26100236/24082047/9a047320-0cbf-11e7-805f-022dae967c15.JPG)

**Comment by RyanQuackenbush** [comment]
Same for latest 2.1.1 version. If you do `?<some-sound> ~` It states is not a valid repeat command. `?<sound-sound> 5` doesn't display an error, but does not actually loop.

@Darkside138 It looks like you have the code for looping [here in the code](https://github.com/Darkside138/DiscordSoundboard/blob/master/src/main/java/net/dirtydeeds/discordsoundboard/ChatSoundBoardListener.java#L227), but haven't uploaded a more recent zip?

**Comment by Darkside138** [comment]
Yeah repeat is broken on the latest versions. It's on the list.
