### ISSUE TITLE
2.0.1 version error with specific yt links

### ISSUE THREAD

**Issue by Scahry** [Darkside138/DiscordSoundboard#59]
i'm currently using the 2.0.1 BETA version which has no problem with most youtube links, but for some specific ones, for example with this one:
https://www.youtube.com/watch?v=SQp1B5WnNjk
I restartet the soundboard but it still occurs so it may be something with the video format or so.
 If it helps you i provided a picture with the whole error:
![unbenannt](https://cloud.githubusercontent.com/assets/26100236/24082121/a7c3d90a-0cc0-11e7-889b-0a92b7de243f.JPG)

**Comment by georgefrick** [comment]
Your version of Java might be old, or it may have just had a connection problem. The link provided appears to be working in the latest.

**Comment by Scahry** [comment]
Thanks, it works now so i was probably late with updating my java
