### ISSUE TITLE
Request: URL or URI Input

### ISSUE THREAD

**Issue by xombiemike** [Darkside138/DiscordSoundboard#60]
I would like to send the bot commands via URL or URI from inside another program. How would I do this?

**Comment by georgefrick** [comment]
You can post to the host URL. When the bot host is running it also runs a web application port :8080 where you can control it. You can look at how those POST commands are done, or look in the file https://github.com/Darkside138/DiscordSoundboard/blob/master/src/main/java/net/dirtydeeds/discordsoundboard/web/SoundboardRestController.java

to see what urls can be posted to.

**Comment by Darkside138** [comment]
It's also running swagger UI that documents the REST API.
