### ISSUE TITLE
"I don't take orders from you" error 

### ISSUE THREAD

**Issue by RBGaming** [Darkside138/DiscordSoundboard#62]
the "allowedUsers=" is empty but i it keeps telling me  "I don't take orders from you".

**Comment by RBGaming** [comment]
hello?

**Comment by FTurman** [comment]
Not a fix, but a workaround: delete the entire "allowedUsers=" line, and anyone should be able to use the bot. It's working on my server.

**Comment by Darkside138** [comment]
Issue resolved in latest beta release 2.1.1
