### ISSUE TITLE
Entrance / Leaving audio clips

### ISSUE THREAD

**Issue by UnfaithfulSin** [Darkside138/DiscordSoundboard#66]
The bot seems to be very hit and miss with this am I doing something wrong? Many times the entrance audio file doesn't get played the leaving one seems to work quite often.

Example
unfaithful sin_Entrance.wav

When I enter I get this error.

[21:48:13] [Info] [EntranceListener]: Could not find any sound that starts with unfaithful sin, so ignoring entrance.

Same with this line, I also had a file called Green_entrance.wav
[22:10:41] [Info] [LeaveListener]: Could not disconnection sound for green, so ignoring disconnection event.

**Comment by z1g** [comment]
I don't think you need to add _entrance to the entrance clips, only the exit clips so maybe try unfaithful sin.wav and green.wav for the enter sounds and unfaithful sin_exit.wav and green_exit.wav for the exit sounds.

**Comment by Darkside138** [comment]
Correct, you don't need to add _entrance to the files. Just name then the same as the user.
