### ISSUE TITLE
List command

### ISSUE THREAD

**Issue by CodexWarz** [Darkside138/DiscordSoundboard#7]
When trying to view the my the of songs that exceed 2000 characters, what is the syntax of the command? It says "?list pageNumber" I try "?list page 1" or something of that extend, but it is an unknown command.

**Comment by Darkside138** [comment]
Type the ?list command followed by the page number. For example: ?list 1

**Comment by CodexWarz** [comment]
I did that, and it tried and it said unknown command, also are you by any
chance adding a shuffle command?

**Comment by Darkside138** [comment]
Can you send me an invite to your server where the bot is running and I'll take a look? I hadn't but that's a good suggestion, I'll look into adding shuffle to the next version.

**Comment by CodexWarz** [comment]
I'm currently not home, you can add me on discord though, CodexWarz#8473

**Comment by CodexWarz** [comment]
I'll be home around 3:30pm eastern

**Comment by Darkside138** [comment]
Yeah no problem I can look tonight. What you say shuffle, do you want continuous playback of random sounds until you issue a /stop command?

**Comment by CodexWarz** [comment]
Yeah, I was looking for a continuous play of all of the songs in the folder where the sound files are located.

**Comment by CodexWarz** [comment]
Link to my server: https://discord.gg/010mPwblswnuZ2pWS

**Comment by CodexWarz** [comment]
The ?random command doesn't work

**Comment by Darkside138** [comment]
Yeah I need to push a new release. Once I do the command will work.

**Comment by CodexWarz** [comment]
When are you planning to do that?

**Comment by Darkside138** [comment]
It's been on my list of things to do for a while now. I'll see if I can get that uploaded this morning. It's all ready to go, just need to push it up to github, :)

**Comment by CodexWarz** [comment]
Sick, once it's uploaded want to jump into my sever and see how it runs?

**Comment by Darkside138** [comment]
OK, new release is available.

**Comment by CodexWarz** [comment]
https://discord.gg/8NrXB

**Comment by CodexWarz** [comment]
That's the link ^

**Comment by Darkside138** [comment]
I believe the ?random and ?list commands are both working properly now. Closing issue.
