### ISSUE TITLE
Could not find sound to play?

### ISSUE THREAD

**Issue by ImNotJoowee** [Darkside138/DiscordSoundboard#71]
For some reason, the bot would instead respond that to me through DM whenever I try to request a sound. Also, before this happened, the bot would join the voice channel, then leave (which I guess kinda fixed it, but then this issue came up).

Any solutions to this?

**Comment by Darkside138** [comment]
It's not finding your sound files. Make sure to check your app.properties file soundDir="". Make sure that is set correctly.
