### ISSUE TITLE
I need to make bot responses for itself's commands. How?

### ISSUE THREAD

**Issue by AHAHACUK** [Darkside138/DiscordSoundboard#72]
Title

**Comment by Darkside138** [comment]
Do you want to know how to change the text that the bot responds with?

**Comment by AHAHACUK** [comment]
No. I want to make bot responds to commands from another bot

**Comment by AHAHACUK** [comment]
or how I can modifier your code?

**Comment by Darkside138** [comment]
You can download the code though GitHub modify and run the build task in
grade
