### ISSUE TITLE
Download of  Beta 2.1.1 not possible

### ISSUE THREAD

**Issue by Jufoli** [Darkside138/DiscordSoundboard#78]
Hellooo!
First of all, thank you very much for your work and the new release last night.
Unfortunatly the download is so slow, that is not possible to finish it (0 Byte/s - 238 KB von 101 MB).
I know it's not your fault but maybe you can upload the releases (zip and tar) somewhere else so we can use a mirror?

Best regards,
Jufoli

**Comment by Darkside138** [comment]
Sure, I can upload somewhere else. Links below. Updated the README as well.

https://nofile.io/f/PvxDRx5qtd2/DiscordSoundboard-2.1.1-beta.tar
https://nofile.io/f/KoGp34M6W1z/DiscordSoundboard-2.1.1-beta.zip
