### ISSUE TITLE
"Could not find sound to play" Error

### ISSUE THREAD

**Issue by chukwumaokere** [Darkside138/DiscordSoundboard#80]
Previously I had the the bot at version 1.9.4 and everything was fine but I switched to 2.1.1 to account for the channel categories, but the issue is that previously i could drag and drop files into the sounds/ dir and it would be ready to play. 
Now with the 2.1.1 update, I cant seem to do that. When I drag and drop a file into sounds/ i get an error that it cant find the sound file. 

Previously the sound dir was set to '' with my 1.9.4 version so I didn't make any major changes when running 2.1.1.

**Comment by Darkside138** [comment]
Yeah, I had to take out the "folder watch" feature for now to get it
working after the categories addition.

**Comment by Darkside138** [comment]
I'm going to add rest endpoint that can be called to update the sound list. This is a temp workaround and I'll add the watch back in later.

**Comment by Darkside138** [comment]
Added the folder watch back in 2.2.0-BETA
