### ISSUE TITLE
Can't "Allow " Users | BETA 2.1.1.

### ISSUE THREAD

**Issue by MHWalker94** [Darkside138/DiscordSoundboard#81]
Assuming I'm understanding this correctly, when there is nothing in the list for allowedUserIds, the bot will respond to all users. So if there is only one name in the list, should the bot only be responding to that one user?

I'm trying to make the bot only respond to myself via chat commands (I can still disable responding to chat commands and use the web browser to play sounds), but can't find a way other than banning all other members, which is tedious and time-consuming. Adding my own user ID (not username) to the list still allows all other members as well as myself to give commands, but adding a user to the Banned list does indeed prevent them from issuing commands.

I don't know if it's a bug or if I'm just not understanding this correctly. Any help would be greatly appreciated.

**Comment by Darkside138** [comment]
No, you are understanding correctly. Must be a bug, I'll take a look when I
have time. Thanks for the report.

**Comment by Darkside138** [comment]
Fixed in 2.2.0-BETA
