### ISSUE TITLE
Stop the bot to switch channels

### ISSUE THREAD

**Issue by NicolasBissig** [Darkside138/DiscordSoundboard#84]
Hey,

for an older version of the Soundboardbot I changed the source code so it won't switch the channels if somebody is joining or leaving a channel that the bot is not currently in. The old version does not work anymore, I think beacause of the "Categories" Discord Update. The new Beta Version is working fine but the bot now automatically joins a channel if somebody connects to the server or disconnects. Is there a way to disable this behavior? (The way i changed the source code half a year ago doesn't work anymore...)

Thank you in advance!

**Comment by Darkside138** [comment]
This should all be working in the latest version. I just need to release it. Look for it soon
