### ISSUE TITLE
Disconnected from WebSocket

### ISSUE THREAD

**Issue by Trytotry2** [Darkside138/DiscordSoundboard#92]
Hello,
My bot is not working anymore, it seems it can't connect to the internet... Do you already know the issue ?

<img width="719" alt="capture" src="https://user-images.githubusercontent.com/20885219/38198112-bc2ca9c6-368b-11e8-94ee-8c41f62a72fe.PNG">

**Comment by dotkeenan** [comment]
same

**Comment by Darkside138** [comment]
Closing due to major new release. This is for the old version.
