### ISSUE TITLE
Remove a soundFile From the list

### ISSUE THREAD

**Issue by qbergman** [Darkside138/DiscordSoundboard#93]
Hello,
I just installed your application and its awesome but there is some functionalities that i didn't see in the documentation and wonder if they exist or it will be possible to implement. How can we remove soundFiles from the list and how can we overwrite a file with the same name ?

**Comment by trew** [comment]
There is an undocumented way to remove files if you have admin permissions on the server. The command is simply:

?remove <sound>

You are also permitted to remove your own entry-sound, even if you aren't admin.

**Comment by Darkside138** [comment]
If you have proper permission you can also private message a file to the bot as an attachment. If the file is already there with the same name it will be replaced
