### ISSUE TITLE
Features...?

### ISSUE THREAD

**Issue by Yukinekos** [Darkside138/DiscordSoundboard#99]
Hi. I recently started to use the bot you have made-- and I'd like to ask. Are there any plans for features like auto-play, shuffle, skip and being able to view what is currently playing?

Thanks.

**Comment by ziotron** [comment]
@Yukinekos The bot is primarily used for soundbites that probably last no longer than 3 seconds. Its not intentionally intended to play full music mp3 songs even though it is fully capable of doing so. Its meant to be a soundboard and not a music player. I do suggest looking into music player bots if you intend on going that route.
